### PR TITLE
An experiment

### PR DESCRIPTION
**Pull request by arcnmx**
I started considering the awkwardness around the `BitFlags<T>` type and why the `RawBitFlags` trait couldn't just be a stable/public API and then this happened. Not sure what to think really, moving everything to a trait just makes a prelude / `*` import necessary but offers a way to reason about generic flags:

- `BitFlagRepr<T>` as a trait encompasses a low-level typed set (or subset) of flags. This is typically either a `BitFlags<T>` (which can hold any of no flags, all flags, or anywhere in between) or a bitflags enum (which can hold exactly one flag). It's responsible for conversions to/from an underlying numeric primitive.
- `BitFlag` is the trait that gets impl'd for the single flag type / the enum, which basically serves the same purpose as `RawBitFlags` does today except it gets extended with a few extensions:
    - It impls `BitFlagRepr` so offers conversions to/from the underlying integer representation (like say `from_bit` for the enum type)
    - It has an associated `Self::Flags` type that can hold a set/collection of flags, to enable things like `Enum::ALL` instead of `BitFlags::<Enum>::all()` and basically just, helper extensions for constructing / referring to a `BitFlags<Enum>`.
- `EnumFlags` (which really should be called `BitFlags` for consistency?) is a generic trait describing a set of `BitFlag`s. Most of the `BitFlags` logic was moved here.
- `BitFlags<T>` impl's `BitFlagsRepr` and `EnumFlags` and serves the same purpose as it does now, except it's been gutted with all functionality actually implemented in the trait.

I have no real goals in mind (yet?), just wanted to reason about things generically and see what happened. I guess partial motivation is in wanting to see if it's feasible to support arbitrary flag structures that aren't tied to a `repr(X)`, as I just remembered I've needed to do in the past with [bitmask arrays](https://github.com/arcnmx/input-linux-rs/blob/master/src/bitmask.rs) that are indexable using [rather large enums](https://github.com/arcnmx/input-linux-rs/blob/master/src/keys.rs) (and thus `1 << discriminator` instead).

### CODE REVIEW

**Comment by NieDzejkob** [comment]
As far as I can see, this wouldn't work for your use case right now since `BitFlag` requires `Copy`.

**Comment by arcnmx** [comment]
Oh sure, this is very WIP and so far mostly just shuffling around the current semantics. I haven't stretched it too far yet to see how generic I want it to be over the underlying representation. The `Copy` constraint would probably\* go away, but that shouldn't be a problem? I'm not sure if there are any reasons that it needs to be Copy; rust will choose the function call ABI it wants to use regardless of whether an argument is a reference or move/copy so references on the traits/fns shouldn't affect performance, and `&self` / autoderef stuff should make it not a big deal for ergonomics either (then conversion traits fill in the gap for arguments / operators?). It may also enable things for object safety too but dunno, that's probably not all that helpful?

(\* well, technically it could stay if I only care about Copy'able underlying types like `[u8;16]` or whatever, but the dynamic `&[u8]` or `Vec<u8>` cases are also kind of also interesting).

**Comment by NieDzejkob** [comment]
As this doesn't seem to actually be solving any use case, I'm closing this for now.

**Comment by arcnmx** [comment]
While I disagree with that assertion, yeah I unfortunately don't have the spare time to flesh it out currently and if there's no interest I can just continue it on as a separate crate.

**Pull request closed without merging**
