### PR TITLE
2018 edition tests

### PR DESCRIPTION
**Pull request by arcnmx**
Builds upon #4 because the no_std tests wouldn't work/pass otherwise. Not included in #4 because this shuffles a lot of test code around and this use of include may be controversial?

### CODE REVIEW

**Comment by NieDzejkob** [comment]
I think the last two commits should be squashed together - at a glance, the second reverts the first one.

**Comment by NieDzejkob** [comment]
To be honest, this is the first time I'm reviewing a PR that mostly moves code around, and I must say that a normal diff is woefully inadequate. I'm now looking for a diff tool that would show this neatly and so far, I've been unsuccessful - nothing shows the code movement between files as actual code movement. I've tried Meld, xxdiff and `git diff --color-merges` so far.

The reason I'm writing this here is that I'm hoping that you have had more experience in this area and can point me toward something reasonable. If not, I'll make do with a normal diff, but I can't see that being pleasant.

**Comment by arcnmx** [comment]
Honestly no idea, git in general does not handle file renames well. If you'd like, I could make a precursor commit that only does the rename that should make the rest easier to review?

IIRC the only changes I made to that file were to:
1. move it outside the tests directory so that cargo doesn't pick it up as an implicit test
    - Though rust 2015 won't do this (once you specify explicit tests, it no longer autodetects them), it warns that 2018 will/might
2. Pull out the parts that aren't common between 2015 and 2018 tests:
    1. extern crates declarations at the top
    2. the module import test

**Comment by NieDzejkob** [comment]
Yes, moving the file rename to a separate commit will make this much easier to follow.

**Pull request merged**
